#!/usr/bin/env python3
import sys
"""
Reddit Sentiment Fetcher for Crypto Trading Bot

Fetches sentiment from Reddit r/crypto, r/bitcoin, r/ethereum communities
using Apify Reddit actor (replaces direct PRAW API).

Grid-validated parameters:
- Half-life: 60 minutes (exponential decay)
- Sources: r/CryptoCurrency, r/Bitcoin, r/ethereum via Apify
- Metrics: Upvotes, comments, sentiment keywords
- Output: reddit_sentiment_cache.json

NO FAKE DATA: Real Reddit data only via Apify actor.
# Switched from dead wVnq9gKj7DKKZQqQe (last success 2026-06-12) to scrapesmith/reddit-scraper
"""

import logging
import os
import json
from datetime import datetime
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
from phase6.core.paths import REDDIT_SENTIMENT_CACHE, load_project_dotenv

try:
    from apify_client import ApifyClient
    APIFY_AVAILABLE = True
except ImportError:
    APIFY_AVAILABLE = False
    ApifyClient = None

try:
    import numpy as np
    NUMPY_AVAILABLE = True
except ImportError:
    NUMPY_AVAILABLE = False
    np = None

try:
    from textblob import TextBlob
    TEXTBLOB_AVAILABLE = True
except ImportError:
    TEXTBLOB_AVAILABLE = False
    TextBlob = None

logger = logging.getLogger(__name__)

def load_full_trading_basket():
    """Load full dynamic basket from config for consistency with runner, x-fetch, rsi-refresher, scorer."""
    try:
        from phase6.core.paths import TRADING_CONFIG_PHASE6
        with open(TRADING_CONFIG_PHASE6) as f:
            cfg = json.load(f)
        pairs = cfg.get("global_settings", {}).get("pairs", []) or cfg.get("phase_6_specific", {}).get("opportunity_pool", [])
        if pairs:
            return pairs
    except Exception:
        pass
    # Fallback to full 11
    return ["BTC-USD", "ETH-USD", "SOL-USD", "XRP-USD", "DOGE-USD", "ADA-USD", "AVAX-USD", "LINK-USD", "UNI-USD", "ARB-USD", "OP-USD"]


# Configuration
REDDIT_CACHE_FILE = REDDIT_SENTIMENT_CACHE
load_project_dotenv()
APIFY_USER_ID = os.getenv('APIFY_USER_ID')
APIFY_API_TOKEN = os.getenv('APIFY_API_TOKEN')

# Apify Reddit actor ID (community actor for scraping Reddit)
REDDIT_ACTOR_ID = os.getenv("REDDIT_APIFY_ACTOR_ID", "scrapesmith/reddit-scraper")  # Cheaper working actor (user suggested). Override via env REDDIT_APIFY_ACTOR_ID if needed.

# Sentiment keywords
BULLISH_KEYWORDS = [
    'moon', 'pump', 'buy', 'bull', 'gain', 'surge', 'spike',
    'awesome', 'great', 'excellent', 'amazing', 'bullish',
    'long', 'hold', 'hodl', 'strong', 'opportunity', 'gem'
]

BEARISH_KEYWORDS = [
    'crash', 'dump', 'sell', 'bear', 'loss', 'drop', 'fall',
    'terrible', 'bad', 'scam', 'bearish', 'short',
    'risk', 'warning', 'caution', 'trap', 'fraud', 'rug'
]


def analyze_sentiment(text: str) -> float:
    """
    Calculate sentiment polarity using TextBlob.
    Falls back to 0.0 if TextBlob unavailable or on error.
    Returns polarity in range [-1.0, 1.0]
    """
    if not TEXTBLOB_AVAILABLE or not text:
        return 0.0
    try:
        return float(TextBlob(text).sentiment.polarity)
    except Exception:
        return 0.0


class RedditSentimentFetcher:
    """Fetch real sentiment from Reddit for crypto pairs via Apify."""
    
    def __init__(self):
        """Initialize Apify client."""
        self.client = None
        # Dynamic full basket for consistent standard
        # Keywords now loaded from central source of truth (config/sentiment_keywords.json)
        # via the defined loader. Updates generated by scripts/optimize_sentiment_keywords.py
        basket = load_full_trading_basket()
        self.pair_keywords = {}

        from phase6.core.sentiment_keywords import get_reddit_keywords
        for pair in basket:
            self.pair_keywords[pair] = get_reddit_keywords(pair)
        
        if not APIFY_AVAILABLE:
            logger.warning("⚠️  ApifyClient not installed. Reddit sentiment disabled.")
            return
        
        if not APIFY_USER_ID or not APIFY_API_TOKEN:
            logger.warning("⚠️  APIFY_USER_ID or APIFY_API_TOKEN not found in environment")
            return
        
        try:
            self.client = ApifyClient(APIFY_API_TOKEN)
            logger.info("✅ Apify client initialized for Reddit sentiment")
        except Exception as e:
            logger.error(f"❌ Apify init failed: {e}")
            self.client = None
    
    def fetch_pair_sentiment(self, pair, subreddits=None):
        """
        Fetch sentiment for a specific pair from Reddit via Apify.
        
        Args:
            pair: Trading pair (e.g., 'BTC-USD')
            subreddits: List of subreddits to search (default: standard crypto subs)
        
        Returns: sentiment_score (-1.0 to 1.0)
        """
        if not self.client:
            logger.warning(f"Apify client not available for {pair}")
            return 0.0
        
        if subreddits is None:
            subreddits = ['CryptoCurrency', 'Bitcoin', 'ethereum']
        
        keywords = self.pair_keywords.get(pair, [pair.split('-')[0].lower()])
        
        try:
            all_posts = []
            
            for subreddit in subreddits:
                for keyword in keywords[:1]:  # Limit to 1 keyword per subreddit to avoid rate limit
                    logger.info(f"  Fetching {pair} from r/{subreddit} (keyword: {keyword})...")
                    
                    # Build Apify actor input
                    run_input = {
                        "startUrls": [
                            {"url": f"https://www.reddit.com/r/{subreddit}/search?q={keyword}&sort=new&t=week"}
                        ],
                        "maxPosts": 30,
                        "proxy": {"useApifyProxy": True}
                    }
                    
                    # Execute actor
                    run = self.client.actor(REDDIT_ACTOR_ID).call(run_input=run_input)
                    
                    # Extract posts from dataset (modern Apify client, works with scrapesmith/solidcode)
                    posts = []
                    try:
                        if hasattr(run, "default_dataset_id"):
                            ds_id = run.default_dataset_id
                        elif isinstance(run, dict):
                            ds_id = run.get("defaultDatasetId") or run.get("data", {}).get("defaultDatasetId")
                        else:
                            ds_id = None
                        if ds_id:
                            items = self.client.dataset(ds_id).list_items(limit=50).items
                            posts = items
                            logger.debug(f"    Got {len(posts)} posts from r/{subreddit} via dataset")
                        else:
                            # Fallback
                            if isinstance(run, dict) and "output" in run:
                                out = run["output"]
                                if isinstance(out, dict) and "posts" in out:
                                    posts = out["posts"]
                    except Exception as e:
                        logger.debug(f"    Extraction error: {e}")
                    all_posts.extend(posts)
            
            if all_posts:
                sentiment = self._calculate_sentiment(all_posts)
                logger.info(f"  {pair}: sentiment={sentiment:.4f} ({len(all_posts)} posts)")
                return sentiment
            else:
                logger.warning(f"  {pair}: No posts found")
                return 0.0
                
        except Exception as e:
            logger.error(f"Error fetching sentiment for {pair}: {e}")
            return 0.0
    
    @staticmethod
    def _calculate_sentiment(posts):
        """
        Calculate sentiment from Reddit posts.
        
        Weights: 
        - Text analysis (TextBlob polarity + keywords): 50%
        - Upvote direction: 30%
        - Comment engagement: 20%
        """
        if not posts:
            return 0.0
        
        total_sentiment = 0.0
        total_weight = 0.0
        
        for post in posts:
            try:
                # Extract post data
                upvotes = int(post.get('upvotes', 0)) or 1
                comments = int(post.get('nComments', 0)) or int(post.get('comments', 0)) or 1
                title = post.get('title', '').lower()
                selftext = post.get('selftext', '').lower() if post.get('selftext') else ''
                
                # Combine text for analysis
                text_content = title + ' ' + selftext
                
                # Text sentiment: hybrid of keyword matching + TextBlob polarity
                bullish_count = sum(1 for word in BULLISH_KEYWORDS if word in text_content)
                bearish_count = sum(1 for word in BEARISH_KEYWORDS if word in text_content)
                
                keyword_sentiment = 0.0
                if bullish_count + bearish_count > 0:
                    keyword_sentiment = (bullish_count - bearish_count) / (bullish_count + bearish_count)
                
                # TextBlob polarity analysis (restored from archived implementation)
                polarity = analyze_sentiment(text_content)
                
                # Hybrid: 60% TextBlob polarity, 40% keyword matching for robustness
                text_sentiment = 0.6 * polarity + 0.4 * keyword_sentiment
                
                # Upvote sentiment (positive upvotes = bullish)
                upvote_sentiment = 1.0 if upvotes > 0 else -1.0
                
                # Comment sentiment (high engagement = confidence)
                comment_sentiment = 1.0 if comments > 5 else (0.0 if comments == 1 else 0.5)
                
                # Weighted combined sentiment
                post_sentiment = (
                    0.5 * text_sentiment +
                    0.3 * upvote_sentiment +
                    0.2 * comment_sentiment
                )
                
                # Weight by engagement (log scale)
                if NUMPY_AVAILABLE:
                    weight = np.log1p(upvotes) + 0.3 * np.log1p(comments)
                else:
                    weight = (upvotes ** 0.5) + 0.3 * (comments ** 0.5)
                
                total_sentiment += post_sentiment * weight
                total_weight += weight
                
            except Exception as e:
                logger.debug(f"Error processing post: {e}")
                continue
        
        # Normalize to [-1, 1]
        if total_weight > 0:
            result = total_sentiment / total_weight
            if NUMPY_AVAILABLE:
                return float(np.clip(result, -1.0, 1.0))
            else:
                return max(-1.0, min(1.0, result))
        else:
            return 0.0
    
    def run(self):
        """Fetch sentiment for all trading pairs."""
        sentiments = {}
        
        for pair in self.pair_keywords.keys():
            sentiment = self.fetch_pair_sentiment(pair)
            sentiments[pair] = sentiment
        
        return sentiments


def save_cache(sentiments):
    """Save Reddit sentiment to cache file."""
    cache_data = {
        pair: {
            'sentiment': score,
            'timestamp': datetime.utcnow().isoformat() + 'Z',
            'source': 'Apify Reddit Actor',
            'subreddits': 'r/CryptoCurrency, r/Bitcoin, r/ethereum'
        }
        for pair, score in sentiments.items()
    }
    
    with open(REDDIT_CACHE_FILE, 'w') as f:
        json.dump(cache_data, f, indent=2)
    
    logger.info(f"💾 Reddit sentiment cache saved to {REDDIT_CACHE_FILE}")
    return cache_data


def main():
    """Run Reddit sentiment fetching."""
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(levelname)s: %(message)s'
    )

    # Hard kill-switch after Apify ~$70/mo burn (2026-07). Default OFF.
    if os.environ.get("SENTIMENT_REDDIT_APIFY_ENABLED", "0").strip().lower() not in (
        "1",
        "true",
        "yes",
        "on",
    ):
        logger.warning(
            "Apify Reddit DISABLED (SENTIMENT_REDDIT_APIFY_ENABLED!=1). "
            "No actor runs. Free shadow + X only."
        )
        print(json.dumps({"skipped": True, "reason": "SENTIMENT_REDDIT_APIFY_ENABLED=0"}, indent=2))
        return

    logger.info("🚀 Starting Reddit sentiment fetch (Apify)...")
    
    fetcher = RedditSentimentFetcher()
    sentiments = fetcher.run()
    
    if sentiments:
        cache_data = save_cache(sentiments)
        print("\n✅ Reddit sentiment aggregation complete")
        print(json.dumps(cache_data, indent=2), flush=True)
    else:
        logger.warning("❌ No Reddit sentiment fetched (Apify may be unavailable)")
        print(json.dumps({}, indent=2), flush=True)


if __name__ == '__main__':
    main()
