.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH msgraph 1  "msgraph " 
.SH NAME
msgraph \- Microsoft Graph CLI
.SH SYNOPSIS
\fBmsgraph\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Microsoft Graph CLI.
.PP
This command gives you access to the Microsoft Graph REST API, organized by Graph resource: the signed\-in user (profile), mail folders, messages and message attachments.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH SUBCOMMANDS
.TP
msgraph\-profile(1)
Manage the Microsoft Graph signed\-in user (`GET /me`)
.TP
msgraph\-mail\-folder(1)
Manage Microsoft Graph mail folders (`me.mailFolders`)
.TP
msgraph\-message(1)
Manage Microsoft Graph messages (`me.messages`)
.TP
msgraph\-attachment(1)
Manage Microsoft Graph message attachments (`me.messages.attachments`)
.TP
msgraph\-help(1)
Print this message or the help of the given subcommand(s)
