.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH mailbox 1  "mailbox " 
.SH NAME
mailbox \- Manage mailboxes using the shared API
.SH SYNOPSIS
\fBmailbox\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage mailboxes using the shared API.
.PP
A mailbox is a message container.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH SUBCOMMANDS
.TP
mailbox\-list(1)
Shared API to list mailboxes for the active account
.TP
mailbox\-help(1)
Print this message or the help of the given subcommand(s)
