.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH envelope 1  "envelope " 
.SH NAME
envelope \- Manage envelopes using the shared API
.SH SYNOPSIS
\fBenvelope\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage envelopes using the shared API.
.PP
An envelope is a message headers subset. It is usually small, and contains enough information to have an overall understanding of what a message is about.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH SUBCOMMANDS
.TP
envelope\-list(1)
List envelopes for the active account, regardless of the underlying backend (IMAP, JMAP or Maildir)
.TP
envelope\-search(1)
Search envelopes for the active account using the shared search query DSL, regardless of the underlying backend (IMAP, JMAP or Maildir)
.TP
envelope\-help(1)
Print this message or the help of the given subcommand(s)
