.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH smtp 1  "smtp " 
.SH NAME
smtp \- SMTP\-specific API
.SH SYNOPSIS
\fBsmtp\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
SMTP\-specific API.
.PP
Gives access to the raw SMTP API. Every CLI command matches the name of its SMTP counterpart.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH SUBCOMMANDS
.TP
smtp\-send(1)
Send a raw RFC 5322 message (MAIL FROM / RCPT TO / DATA)
.TP
smtp\-raw(1)
Send a raw SMTP command and print the verbatim reply
.TP
smtp\-help(1)
Print this message or the help of the given subcommand(s)
