.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH completion 1  "completion " 
.SH NAME
completion \- Generate completion script for the give shell(s) to the given directory
.SH SYNOPSIS
\fBcompletion\fR [\fB\-d\fR|\fB\-\-dir\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fISHELLS\fR] 
.SH DESCRIPTION
Generate completion script for the give shell(s) to the given directory.
.PP
This command allows you to generate completion script for a given shell. The script is printed to the standard output. If you want to write it to a file, just use unix redirection.
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-dir\fR \fI<PATH>\fR [default: ./]
Save completion script to the given directory
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fISHELLS\fR]
Shell for which completion script should be generated for
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
bash
.IP \(bu 2
elvish
.IP \(bu 2
fish
.IP \(bu 2
powershell
.IP \(bu 2
zsh
.RE
