.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH json-schema 1  "json-schema " 
.SH NAME
json\-schema \- Generate JSON Schemas of every command\*(Aqs JSON output to the given directory
.SH SYNOPSIS
\fBjson\-schema\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIDIR\fR> 
.SH DESCRIPTION
Generate JSON Schemas of every command\*(Aqs JSON output to the given directory.
.PP
This command allows you to generate one JSON Schema per command describing the structure of its `\-\-json` output, to the given directory. If the directory does not exist, it will be created. Any existing schema will be overriden.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
<\fIDIR\fR>
Directory where JSON Schema files should be generated in
