.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH gmail 1  "gmail " 
.SH NAME
gmail \- Gmail\-specific API
.SH SYNOPSIS
\fBgmail\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Gmail\-specific API.
.PP
This command gives you access to the raw Gmail REST API, organized by Gmail resource: profile, labels, messages (and attachments), drafts, threads, history and settings.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.SH SUBCOMMANDS
.TP
gmail\-profile(1)
Manage the Gmail user profile (users.getProfile)
.TP
gmail\-labels(1)
Manage Gmail labels (users.labels)
.TP
gmail\-messages(1)
Manage Gmail messages (users.messages)
.TP
gmail\-attachments(1)
Manage Gmail message attachments (messages.attachments)
.TP
gmail\-drafts(1)
Manage Gmail drafts (users.drafts)
.TP
gmail\-threads(1)
Manage Gmail threads (users.threads)
.TP
gmail\-history(1)
Manage the Gmail mailbox history (users.history)
.TP
gmail\-settings(1)
Manage Gmail settings (users.settings), organized by sub\-resource
.TP
gmail\-help(1)
Print this message or the help of the given subcommand(s)
