from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, Enum as SQLEnum, Text, JSON
from sqlalchemy.dialects.postgresql import UUID, JSONB
import uuid
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime
import enum
import os
from cryptography.fernet import Fernet, InvalidToken

Base = declarative_base()

# Encryption helper for oauth_tokens (at rest)
# Requires ENCRYPTION_KEY in env (base64 32-byte key, e.g. generated by Fernet.generate_key())
ENCRYPTION_KEY = os.getenv("ENCRYPTION_KEY")
if ENCRYPTION_KEY:
    try:
        _fernet = Fernet(ENCRYPTION_KEY.encode() if isinstance(ENCRYPTION_KEY, str) else ENCRYPTION_KEY)
    except Exception:
        _fernet = None
else:
    _fernet = None


def encrypt_value(value: str) -> str:
    """Encrypt string value for storage. Returns base64-like token or plaintext if no key (dev only)."""
    if not value:
        return None
    if _fernet is None:
        # Dev fallback - DO NOT USE IN PROD. Log warning in real code.
        return f"DEV_PLAINTEXT:{value}"
    try:
        return _fernet.encrypt(value.encode()).decode()
    except Exception:
        return None


def decrypt_value(enc_value: str) -> str:
    """Decrypt stored value. Returns plaintext or None."""
    if not enc_value:
        return None
    if enc_value.startswith("DEV_PLAINTEXT:"):
        return enc_value[len("DEV_PLAINTEXT:"):]
    if _fernet is None:
        return None
    try:
        return _fernet.decrypt(enc_value.encode()).decode()
    except (InvalidToken, Exception):
        return None


class TraderStatus(enum.Enum):
    DISCONNECTED = "disconnected"
    CONNECTED = "connected"
    ERROR = "error"
    REVOKED = "revoked"


class BillingStatus(enum.Enum):
    ACTIVE = "active"
    PAST_DUE = "past_due"
    CANCELED = "canceled"
    TRIALLING = "trialing"
    NONE = "none"


class AuthMode(enum.Enum):
    OAUTH = "oauth"
    API_KEY = "api_key"


class Tier(enum.Enum):
    STARTER = "starter"
    PRO = "pro"
    ELITE = "elite"


class JobStatus(enum.Enum):
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    CANCELLED = "cancelled"


class Trader(Base):
    """Primary multi-tenant trader / account registry. Canonical state in Postgres."""
    __tablename__ = "traders"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    # GHL linkage
    ghl_contact_id = Column(String(100), unique=True, index=True, nullable=True)
    ghl_location_id = Column(String(100), nullable=True)
    # Coinbase linkage (portfolio_uuid preferred post 2025)
    portfolio_uuid = Column(String(100), unique=True, index=True, nullable=True)
    # coinbase_account_id kept for compatibility if needed
    coinbase_account_id = Column(String(100), unique=True, index=True, nullable=True)

    tier = Column(SQLEnum(Tier), default=Tier.STARTER, nullable=False)
    billing_status = Column(SQLEnum(BillingStatus), default=BillingStatus.NONE, nullable=False)
    coinbase_status = Column(SQLEnum(TraderStatus), default=TraderStatus.DISCONNECTED, nullable=False)
    auth_mode = Column(SQLEnum(AuthMode), default=AuthMode.OAUTH, nullable=False)

    # Timestamps and telemetry
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)
    last_cycle_at = Column(DateTime, nullable=True)
    last_rebalance_at = Column(DateTime, nullable=True)
    last_sync_at = Column(DateTime, nullable=True)

    # Free form flags / notes
    flags = Column(JSON, default=dict)  # e.g. {"paused": false, "pilot": true}
    notes = Column(Text, nullable=True)

    # Relationships
    config = relationship("TraderConfig", back_populates="trader", uselist=False, cascade="all, delete-orphan")
    oauth_token = relationship("OAuthToken", back_populates="trader", uselist=False, cascade="all, delete-orphan")
    job_runs = relationship("JobRun", back_populates="trader", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Trader id={self.id} portfolio={self.portfolio_uuid} tier={self.tier} status={self.coinbase_status}>"


class TraderConfig(Base):
    """Per-trader overrides and settings. Snapshot + overrides."""
    __tablename__ = "trader_configs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    trader_id = Column(UUID(as_uuid=True), ForeignKey("traders.id"), nullable=False, unique=True)

    # Flexible storage: use JSONB for complex params
    pairs = Column(JSON, default=list)  # e.g. ["BTC-USD", "ETH-USD"]
    risk_params = Column(JSON, default=dict)  # e.g. {"max_position_pct": 0.25, "sl_pct": 0.05}
    allocation_overrides = Column(JSON, default=dict)
    rebalance_frequency = Column(String(20), default="daily")
    max_deploy_usd = Column(Float, nullable=True)
    pair_count_cap = Column(Integer, default=6)

    # Full snapshot of tier defaults at provisioning time + user overrides
    tier_template_snapshot = Column(JSON, default=dict)
    overrides = Column(JSON, default=dict)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    trader = relationship("Trader", back_populates="config")

    def __repr__(self):
        return f"<TraderConfig trader_id={self.trader_id} pairs={len(self.pairs or [])}>"


class OAuthToken(Base):
    """Encrypted OAuth tokens at rest. Never plaintext in DB or logs."""
    __tablename__ = "oauth_tokens"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    trader_id = Column(UUID(as_uuid=True), ForeignKey("traders.id"), nullable=False, unique=True)

    access_token_enc = Column(Text, nullable=False)  # encrypted via encrypt_value
    refresh_token_enc = Column(Text, nullable=True)
    expires_at = Column(DateTime, nullable=True)
    scopes = Column(JSON, nullable=True)  # or String
    portfolio_uuid = Column(String(100), nullable=True)  # denormalized for convenience

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    trader = relationship("Trader", back_populates="oauth_token")

    def set_tokens(self, access_token: str, refresh_token: str = None, expires_at=None, scopes=None):
        self.access_token_enc = encrypt_value(access_token)
        if refresh_token:
            self.refresh_token_enc = encrypt_value(refresh_token)
        self.expires_at = expires_at
        self.scopes = scopes

    def get_access_token(self) -> str:
        return decrypt_value(self.access_token_enc)

    def get_refresh_token(self) -> str:
        return decrypt_value(self.refresh_token_enc)

    def __repr__(self):
        return f"<OAuthToken trader_id={self.trader_id} expires={self.expires_at}>"


class JobRun(Base):
    """Audit / metrics log for each runner cycle per account."""
    __tablename__ = "job_runs"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    trader_id = Column(UUID(as_uuid=True), ForeignKey("traders.id"), nullable=False, index=True)
    run_id = Column(String(100), nullable=False, index=True)  # e.g. uuid or timestamped id

    started_at = Column(DateTime, default=datetime.utcnow, nullable=False)
    ended_at = Column(DateTime, nullable=True)
    status = Column(SQLEnum(JobStatus), default=JobStatus.PENDING, nullable=False)

    # Structured metrics / summary
    metrics = Column(JSON, default=dict)  # {"pairs_traded": 3, "rebal_count":1, "sl_events":0, "error": None, "deployed_pct": 0.42, ...}

    error_summary = Column(Text, nullable=True)
    duration_seconds = Column(Float, nullable=True)

    trader = relationship("Trader", back_populates="job_runs")

    def __repr__(self):
        return f"<JobRun trader={self.trader_id} run={self.run_id} status={self.status}>"


# Legacy tables kept for reference / migration path (from initial 001). Not used for multi-tenant registry.
# In T0+ they may be dropped or remain for shared intel (prices etc) if reused.
class LegacyTradeStatus(enum.Enum):
    PENDING = "pending"
    FILLED = "filled"
    CANCELLED = "cancelled"


class LegacySignalAction(enum.Enum):
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


class LegacyTrader(Base):
    __tablename__ = "legacy_traders"
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    name = Column(String(100), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)


# Note: other legacy (pairs, prices, trades, signals) from 001 can stay or be migrated separately.
# For T0 registry focus we prioritize traders + related.
