#!/usr/bin/env python3
"""
optimize_sentiment_keywords.py

A tool to determine the most relevant keyword(s) for each trading pair
currently tracked on the platform.

It tests:
- Trading pair abbreviation (e.g. "XRP", "ETH", "$XRP")
- Formal / common name (e.g. "ripple", "ethereum", "bitcoin")
- Combinations

Scoring emphasizes **trading relevance** for accurate trading decisions:
- Raw post volume (discussion level)
- Count and ratio of posts containing trading slang / price-action language
- Uses a base + crypto-specific lexicon (inspired by validated lexicons + community slang)

Lexicon approach (from research + crypto practice):
- Base: general positive/negative from NRC/Bing/Loughran-McDonald style
- Crypto-specific extensions: moon, pump, ATH, FUD, rug pull, rekt, WAGMI, etc.
- Slang is weighted more heavily because it carries stronger intensity in crypto communities.
- The tool can be extended to continuously mine new terms from real posts.

Recommended workflow (as discussed):
1. Start with validated base lexicons.
2. Add crypto-specific slang from r/CryptoCurrency, Twitter, etc.
3. Weight slang higher.
4. Re-run this tool periodically as language evolves.

Usage:
  python scripts/optimize_sentiment_keywords.py                  # full current basket on X
  python scripts/optimize_sentiment_keywords.py --pairs XRP-USD,BTC-USD
  python scripts/optimize_sentiment_keywords.py --source x,reddit --max-posts 15

Outputs a clear per-pair recommendation + detailed JSON report.
Can suggest patches to the production fetch_x_sentiment.py and fetch_reddit_sentiment.py maps.

Real data only. Conservative API usage.
"""

import sys
from pathlib import Path
# Make sure we can import phase6.* when running the script directly
sys.path.insert(0, str(Path(__file__).parent.parent))


import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from collections import defaultdict


# from phase6... moved to runtime import inside functions for robustness
    get_current_basket, check_for_new_pairs, 
    load_sentiment_keywords, get_x_keyword, get_reddit_keywords
)

def load_and_merge_keywords(new_recommendations: dict):
    """Merge optimizer results into the central config file."""
    keywords_file = BASE_DIR / "config" / "sentiment_keywords.json"
    if keywords_file.exists():
        with open(keywords_file) as f:
            data = json.load(f)
    else:
        data = {"version": 1, "pairs": {}}

    data["last_updated"] = datetime.utcnow().isoformat() + "Z"
    data["method"] = "Updated via scripts/optimize_sentiment_keywords.py (trading relevance scoring)"

    for pair, rec in new_recommendations.items():
        if pair not in data["pairs"]:
            data["pairs"][pair] = {}
        data["pairs"][pair]["x"] = rec.get("x", rec.get("best_query", _get_ticker(pair)))
        data["pairs"][pair]["reddit"] = rec.get("reddit", [rec.get("best_query", _get_ticker_lower(pair))])
        data["pairs"][pair]["notes"] = rec.get("notes", "Generated by optimizer tool")

    keywords_file.parent.mkdir(parents=True, exist_ok=True)
    with open(keywords_file, "w") as f:
        json.dump(data, f, indent=2)
    print(f"Updated central keywords file: {keywords_file}")
    return data

BASE_DIR = Path("/home/brad/projects/crypto-trading-bot")
CONFIG_PATH = BASE_DIR / "config" / "trading_config_phase6.json"
ENV_FILE = BASE_DIR / ".env"
REPORT_PATH = BASE_DIR / "data" / "state" / "keyword_optimization_report.json"

# === TRADING RELEVANCE LEXICON (base + crypto-specific) ===
# Positive (validated + crypto slang)
POSITIVE_BASE = [
    "bullish", "optimistic", "gain", "growth", "strong", "support", "breakout",
    "surge", "momentum", "improve", "recover", "confidence", "opportunity",
    "excited", "hopeful", "win", "advantage", "rally", "green"
]
POSITIVE_CRYPTO = [
    "moon", "mooning", "to the moon", "pump", "pumping", "send it", "ath",
    "all time high", "bull run", "bullish af", "mega bullish", "rocket", "🚀",
    "parabolic", "whale buying", "accumulating", "load up", "green candles",
    "wagmi", "based", "printing", "cook", "ngmi"  # some overlap with negative but context matters
]

# Negative (validated + crypto slang)
NEGATIVE_BASE = [
    "bearish", "negative", "fear", "risk", "loss", "drop", "crash", "collapse",
    "weak", "uncertain", "panic", "sell", "dump", "decline", "volatile",
    "concern", "bad", "danger", "sell-off", "bloodbath", "red"
]
NEGATIVE_CRYPTO = [
    "rug pull", "scam", "exit liquidity", "dumping", "rekt", "liquidated",
    "bear market", "bearish af", "fud", "fear uncertainty doubt", "dead coin",
    "trash", "garbage project", "red candles", "ngmi"
]

ALL_TRADING_WORDS = set(POSITIVE_BASE + POSITIVE_CRYPTO + NEGATIVE_BASE + NEGATIVE_CRYPTO)

def count_trading_relevance(text: str) -> int:
    """Returns how many trading-relevant tokens are in the text (higher = stronger signal)."""
    text_lower = text.lower()
    score = 0
    for word in ALL_TRADING_WORDS:
        if word in text_lower:
            score += 1
    # Bonus for strong crypto slang
    strong_slant = ["moon", "pump", "ath", "fud", "rug", "rekt", "wagmi", "🚀"]
    for w in strong_slant:
        if w in text_lower:
            score += 1
    return score

def load_bearer_token() -> str:
    if not ENV_FILE.exists():
        return ""
    for line in open(ENV_FILE):
        if line.strip().startswith("X_API_BEARER"):
            return line.split("=", 1)[1].strip().strip('"\'')
    return ""

def load_apify_token() -> str:
    if not ENV_FILE.exists():
        return ""
    for line in open(ENV_FILE):
        if line.strip().startswith("APIFY_API_TOKEN"):
            return line.split("=", 1)[1].strip().strip('"\'')
    return ""

def load_current_basket():
    try:
        cfg = json.load(open(CONFIG_PATH))
        pairs = (cfg.get("global_settings", {}).get("pairs") or
                 cfg.get("phase_6_specific", {}).get("opportunity_pool") or [])
        if not pairs:
            pairs = ["BTC-USD", "ETH-USD", "SOL-USD", "XRP-USD", "DOGE-USD",
                     "ADA-USD", "AVAX-USD", "LINK-USD", "UNI-USD", "ARB-USD", "OP-USD"]
        return pairs
    except Exception:
        return ["BTC-USD", "ETH-USD", "SOL-USD", "XRP-USD", "DOGE-USD",
                "ADA-USD", "AVAX-USD", "LINK-USD", "UNI-USD", "ARB-USD", "OP-USD"]

# Formal name suggestions (for testing both abbreviation and name)
FORMAL_NAME_MAP = {
    "BTC-USD": ["bitcoin", "btc"],
    "ETH-USD": ["ethereum", "eth"],
    "SOL-USD": ["solana", "sol"],
    "XRP-USD": ["xrp", "ripple"],   # deliberately test the controversial one
    "DOGE-USD": ["dogecoin", "doge"],
    "ADA-USD": ["cardano", "ada"],
    "AVAX-USD": ["avalanche", "avax"],
    "LINK-USD": ["chainlink", "link"],
    "UNI-USD": ["uniswap", "uni"],
    "ARB-USD": ["arbitrum", "arb"],
    "OP-USD": ["optimism", "op"],
}

def generate_candidates(pair: str):
    """Generate a rich set of candidates to test for a pair."""
    ticker = pair.split("-")[0].upper()
    lower = ticker.lower()
    candidates = {
        f"{ticker} (ticker)": ticker,
        f"${ticker} (dollar)": f"${ticker}",
        f"{lower} (lower)": lower,
    }

    names = FORMAL_NAME_MAP.get(pair, [lower])
    for name in names:
        if name != lower:
            candidates[f"{name} (name)"] = name

    # Test explicit OR for controversial cases
    if pair == "XRP-USD":
        candidates["XRP OR ripple"] = "XRP OR ripple"
        candidates["$XRP OR ripple"] = "$XRP OR ripple"

    if pair == "BTC-USD":
        candidates["BTC OR bitcoin"] = "BTC OR bitcoin"

    return candidates

def fetch_x_for_candidates(bearer: str, candidates: dict, max_results: int = 10):
    """Test each candidate on X recent search. Returns scored results."""
    import requests
    results = {}
    url = "https://api.twitter.com/2/tweets/search/recent"
    headers = {"Authorization": f"Bearer {bearer}"}

    for label, query in candidates.items():
        params = {
            "query": f"{query} -scam -is:retweet",
            "max_results": min(max_results, 10),
            "tweet.fields": "text,public_metrics",
        }
        try:
            resp = requests.get(url, headers=headers, params=params, timeout=15)
            if resp.status_code != 200:
                results[label] = {"count": 0, "trading_score": 0, "ratio": 0, "sample": f"API error {resp.status_code}", "query": query}
                continue

            posts = resp.json().get("data", []) or []
            count = len(posts)

            total_trading = 0
            for p in posts:
                text = p.get("text", "")
                total_trading += count_trading_relevance(text)

            ratio = total_trading / max(1, count) if count else 0
            sample = posts[0].get("text", "")[:110].replace("\n", " ") if posts else "(no posts)"

            results[label] = {
                "count": count,
                "trading_score": total_trading,
                "ratio": round(ratio, 2),
                "sample": sample,
                "query": query
            }
        except Exception as e:
            results[label] = {"count": 0, "trading_score": 0, "ratio": 0, "sample": str(e)[:60], "query": query}

    return results

def main():
    print("Sentiment Keyword Optimizer Tool")
    print(f"Timestamp: {datetime.utcnow().isoformat()}")
    print("Goal: Find keywords that surface the strongest *trading-relevant* signals (price action, slang, conviction) for accurate decisions.")
    print("Lexicon: Base validated + heavy crypto-specific slang weighting.\n")

    bearer = load_bearer_token()
    if not bearer:
        print("❌ No X_API_BEARER token found. Cannot run X tests.")
        sys.exit(1)

    pairs = load_current_basket()
    print(f"Testing basket ({len(pairs)} pairs): {pairs}\n")

    all_results = {}

    for pair in pairs:
        print(f"\n=== {pair} ===")
        candidates = generate_candidates(pair)
        x_results = fetch_x_for_candidates(bearer, candidates, max_results=10)

        # Pick best by trading_score (primary), then ratio, then volume
        best_label = max(x_results.items(), key=lambda x: (x[1]["trading_score"], x[1]["ratio"], x[1]["count"]))[0]
        best = x_results[best_label]

        print(f"  Best: {best_label}")
        print(f"    Posts: {best['count']} | Trading score: {best['trading_score']} | Ratio: {best['ratio']}")
        print(f"    Sample: {best['sample']}")

        all_results[pair] = {
            "candidates": x_results,
            "recommendation": {
                "best_label": best_label,
                "best_query": best["query"],
                "trading_score": best["trading_score"],
                "posts": best["count"],
                "ratio": best["ratio"]
            }
        }

    # Summary table
    print("\n\n=== RECOMMENDATIONS (sorted by trading signal strength) ===")
    sorted_pairs = sorted(all_results.items(), key=lambda x: x[1]["recommendation"]["trading_score"], reverse=True)
    for pair, data in sorted_pairs:
        rec = data["recommendation"]
        print(f"{pair:12s} → {rec['best_label']:25s} (score={rec['trading_score']:3d}, posts={rec['posts']:2d}, ratio={rec['ratio']})")

    # Save detailed report
    REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(REPORT_PATH, "w") as f:
        json.dump({
            "timestamp": datetime.utcnow().isoformat(),
            "basket": pairs,
            "lexicon_note": "Base validated lexicons + crypto slang (moon/pump/ATH/FUD/rug/rekt etc.) weighted heavily for trading intensity.",
            "results": all_results,
            "note": "Use the 'best_query' values to update KEYWORD_MAP / pair_keywords in the fetch scripts."
        }, f, indent=2)

    print(f"\nDetailed report saved to {REPORT_PATH}")
    print("\nNext steps:")
    print("- Review samples for qualitative quality.")
    print("- Run with --apply (future) or manually patch the fetch scripts with the best queries.")
    print("- Re-run periodically as crypto language evolves.")



def _get_ticker(pair):
    return pair.split("-")[0].upper()

def _get_ticker_lower(pair):
    return pair.split("-")[0].lower()



if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Sentiment Keyword Optimizer & Manager")
    parser.add_argument("--pairs", help="Comma-separated list of pairs to test (default: full current basket)")
    parser.add_argument("--check-new-pairs", action="store_true", help="Check which pairs in the trading basket have no explicit keywords yet")
    parser.add_argument("--refresh", action="store_true", help="Run optimization for the basket and update config/sentiment_keywords.json")
    args = parser.parse_args()

    if args.check_new_pairs:
        from phase6.core.sentiment_keywords import check_for_new_pairs
        new = check_for_new_pairs()
        if new:
            print("New pairs needing keyword optimization:", new)
            print("Run the tool (without --check-new-pairs) on these pairs to generate recommendations.")
        else:
            print("No new pairs. All current basket pairs have explicit keyword entries.")
        exit(0)

    # Run the core optimization (the main() function defined earlier in the file)
    main()

    if args.refresh:
        print("\n=== --refresh requested ===")
        print("To implement automatic write-back, capture results from the run above and call load_and_merge_keywords().")
        print("For now:")
        print("  1. Review the printed recommendations and samples")
        print("  2. Manually edit config/sentiment_keywords.json if needed, or extend this script")
        print("  3. The fetch scripts will automatically pick up changes on next run via the loader.")
