"""
Comparison Report Generator

Generates side-by-side markdown reports for Baseline vs Expanded runs.
"""

from typing import Dict
from phase6.backtest.metrics import collect_metrics


def generate_comparison_report(baseline: Dict, expanded: Dict) -> str:
    """Generate a simple markdown comparison report."""
    lines = [
        "# Phase 6 Backtest Comparison Report",
        "",
        "## Baseline vs Expanded",
        "",
        "| Metric                  | Baseline     | Expanded     | Delta      |",
        "|-------------------------|--------------|--------------|------------|",
    ]

    for key in baseline:
        b_val = baseline[key]
        e_val = expanded.get(key, "N/A")
        delta = "—" if e_val == "N/A" else round(e_val - b_val, 2) if isinstance(b_val, (int, float)) else "—"
        lines.append(f"| {key:<23} | {b_val:<12} | {e_val:<12} | {delta:<10} |")

    lines.append("")
    lines.append("_Report generated by Phase 6 Backtest Harness (Phase 1)_")
    return "\n".join(lines)


if __name__ == "__main__":
    print("Report module initialized (Phase 1)")